server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/seeeeeeong/spring-cloud-config
#          uri: file:///Users/leesinseong/desktop/work/git-local-repo